services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: myproduct
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  myproduct:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myproduct
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  postgres_data:
